version: '3.7'

services:

    nuxt:
        build:
            context: nuxt
            args:
                - NODE_VERSION=${NODE_VERSION}
                - UID=${UID}
                - GID=${GID}
        command: bash -c "tail -F anything"
        working_dir: /usr/share/nginx/html
        volumes:
            - ./nuxt_project:/usr/share/nginx/html
        environment:
            - HOST=0.0.0.0
        user: "${UID}:${GID}"
        ports:
            - ${NUXT_PORT}:3000
